.PHONY: install run

help:
	@echo "install - install dependencies for running tests"
	@echo "run - run tests"

install:
	python3 -m pip install -r requirements.txt

run:
	python3 -u -m pytest -v -r s -x

